{% set name = "python-semantic-release" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d5a6b8f3641db93790a91aee61e3561befd083594c8295152062540ca1e57fd

build:
  noarch: python
  number: 0
  entry_points:
    - semantic-release=semantic_release.cli:main
    - psr=semantic_release.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=8,<9.0
    - dotty-dict >=1.3.0,<2
    - gitpython >=3.0.8,<4
    - importlib-resources >=5.7,<7
    - jinja2 >=3.1.2,<4
    - pydantic >=2,<3
    - python >=3.7
    - python-gitlab >=2,<4
    - requests >=2.25,<3
    - rich >=12.5.1
    - shellingham >=1.5.0
    - tomlkit >=0.10,<1

test:
  requires:
    - git
  imports:
    - semantic_release
  commands:
    - semantic-release --help

about:
  home: http://github.com/relekang/python-semantic-release
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic semantic versioning for python projects
  doc_url: https://python-semantic-release.readthedocs.io/en/latest/
  dev_url: https://github.com/relekang/python-semantic-release
  description: Automatic semantic versioning for python projects. This is an python implementation of the semantic-release for js by Stephan Bönnemann. If you find this topic interesting you should check out his talk from JSConf Budapest.

extra:
  recipe-maintainers:
    - timkpaine
    - KingDarBoja
