{% set name = "python-semantic-release" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f685c0145dc0d192bb133f5ab682608d3f92aa7fdbcd3268c2e404233afc6d8

build:
  noarch: python
  number: 0
  entry_points:
    - semantic-release=semantic_release.cli:entry
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7,<9.0
    - click-log >=0.3,<1
    - gitpython >=3.0.8,<4
    - invoke >=1.4.1,<3
    - python >=3.7
    - python-gitlab >=2,<4
    - requests >=2.25,<3
    - semver >=2.10,<3
    - tomlkit >=0.10,<1
    - dotty-dict >=1.3.0,<2
    - twine >=3,<4
    - wheel
    - packaging

test:
  requires:
    - git
  imports:
    - semantic_release
    - semantic_release.history
  commands:
    - semantic-release --help

about:
  home: http://github.com/relekang/python-semantic-release
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic semantic versioning for python projects
  doc_url: https://python-semantic-release.readthedocs.io/en/latest/
  dev_url: https://github.com/relekang/python-semantic-release
  description: Automatic semantic versioning for python projects. This is an python implementation of the semantic-release for js by Stephan Bönnemann. If you find this topic interesting you should check out his talk from JSConf Budapest.

extra:
  recipe-maintainers:
    - timkpaine
    - KingDarBoja
