{% set name = "python-semantic-release" %}
{% set version = "9.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 19ac268bc417b2b8ea869caede307c50bc1fc2c6c70ee42e88403e321d13f494

build:
  noarch: python
  number: 0
  entry_points:
    - semantic-release=semantic_release.cli.commands.main:main
    - psr=semantic_release.cli.commands.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click >=8,<9.0
    - click-option-group >=0.5,<0.6
    - dotty-dict >=1.3.0,<2
    - gitpython >=3.0.8,<4
    - importlib-resources >=5.7,<7
    - jinja2 >=3.1.2,<4
    - pydantic >=2,<3
    - python >=3.8
    - python-gitlab >=2,<5
    - requests >=2.25,<3
    - rich >=13,<14
    - shellingham >=1.5.0
    - tomlkit >=0.11,<1

test:
  requires:
    - git
    - pip
  imports:
    - semantic_release
  commands:
    - pip check
    - semantic-release --help

about:
  home: http://github.com/relekang/python-semantic-release
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic semantic versioning for python projects
  doc_url: https://python-semantic-release.readthedocs.io/en/latest/
  dev_url: https://github.com/relekang/python-semantic-release
  description: Automatic semantic versioning for python projects. This is an python implementation of the semantic-release for js by Stephan Bönnemann. If you find this topic interesting you should check out his talk from JSConf Budapest.

extra:
  recipe-maintainers:
    - timkpaine
    - KingDarBoja
