{% set name = "python-semantic-release" %}
{% set version = "7.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb9db4b07963b4ba2ad92c3366895d22fa12e5eeb93394f7c73e752429134039

build:
  noarch: python
  number: 0
  entry_points:
    - semantic-release=semantic_release.cli:entry
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click >=7,<8.0
    - click-log >=0.3,<1
    - gitpython >=3.0.8,<4
    - invoke >=1.4.1,<2
    - python
    - python-gitlab >=1.10,<2
    - requests >=2.25,<3
    - semver >=2.8,<3
    - toml ==0.10.0
    - twine >=3,<4
    - wheel

test:
  requires:
    - git
  imports:
    - semantic_release
    - semantic_release.history
  commands:
    - semantic-release --help

about:
  home: http://github.com/relekang/python-semantic-release
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic semantic versioning for python projects
  doc_url: https://python-semantic-release.readthedocs.io/en/latest/
  dev_url: https://github.com/relekang/python-semantic-release
  description: Automatic semantic versioning for python projects. This is an python implementation of the semantic-release for js by Stephan Bönnemann. If you find this topic interesting you should check out his talk from JSConf Budapest.

extra:
  recipe-maintainers:
    - KingDarBoja
