{% set name = "python-semantic-release" %}
{% set version = "10.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16003292315ee29b6ad424fad9745946422cf965e19649269c4e2fb8271cb267

build:
  noarch: python
  number: 0
  entry_points:
    - semantic-release=semantic_release.cli.commands.main:main
    - psr=semantic_release.cli.commands.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8,<9.0
    - click-option-group >=0.5,<0.6
    - gitpython >=3.0.8,<4
    - requests >=2.25,<3
    - jinja2 >=3.1.2,<4
    - python-gitlab >=4,<6
    - tomlkit >=0.11,<1
    - dotty-dict >=1.3.0,<2
    - importlib-resources >=6,<7
    - pydantic >=2,<3
    - rich >=14,<15
    - shellingham >=1.5.0
    - deprecated >=1.2,<1.3

test:
  requires:
    - git
    - pip
    - python {{ python_min }}
  imports:
    - semantic_release
  commands:
    - pip check
    - semantic-release --help

about:
  home: http://github.com/relekang/python-semantic-release
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic semantic versioning for python projects
  doc_url: https://python-semantic-release.readthedocs.io/en/latest/
  dev_url: https://github.com/relekang/python-semantic-release
  description: Automatic semantic versioning for python projects. This is an python implementation of the semantic-release for js by Stephan Bönnemann. If you find this topic interesting you should check out his talk from JSConf Budapest.

extra:
  recipe-maintainers:
    - timkpaine
    - KingDarBoja
